name: test

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:

jobs:
  image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build image
        run: docker build -t image:local -f Dockerfile .

      - name: Try to execute
        run: docker run --rm image:local --help

      - name: Get open-rpc examples
        uses: actions/checkout@v2
        with:
          repository: open-rpc/examples # Link: <https://github.com/open-rpc/examples/>

      - name: List
        run: find ./service-descriptions -iname '*.json' -exec echo "File is {}" \;
